language: cpp

sudo: false

cache:
    - directories:
        - $HOME/cmake
        - $HOME/lib

matrix:
    include:
        - os: linux
          compiler: gcc
          addons:
              apt:
                sources: ['ubuntu-toolchain-r-test']
                packages:
                  - gcc-4.9
                  - g++-4.9
                  - libx11-dev
                  - libgl1-mesa-dev
                  - xorg-dev
                  - libglu1-mesa-dev
                  - libglew-dev
                  - libopenal-dev
                  - lua5.2
                  - liblua5.2-dev
          env: COMPILER=g++-4.9

    allow_failures:
        - os: linux
          compiler: clang
          addons:
              apt:
                sources:
                    - ubuntu-toolchain-r-test
                    - llvm-toolchain-precise-3.7
                packages:
                  - clang-3.7
                  - libx11-dev
                  - libgl1-mesa-dev
                  - xorg-dev
                  - libglu1-mesa-dev
                  - libglew-dev
                  - libopenal-dev
          env: COMPILER=clang++-3.7


before_install:
  - git submodule update --init
  - export CXX="$COMPILER"
  - ${CXX} --version
  - echo $LANG
  - echo $LC_ALL
    # Grabs Cmake 3.2
  - ./travis/install_cmake.sh
  - ls $HOME/cmake/
  - export PATH=$HOME/cmake/:$HOME/cmake/bin/:$PATH
  - cmake --version

install:

before_script:
  - pwd
  - mkdir build
  - cd build

script:
  - ../travis/build_deps.sh
  #- cmake ..
  #- make
  #- make install DESTDIR="$HOME/lib/$COMPILER"
  - echo "Building TEC"
  - rm -f cmakecache.txt
  - cmake -DCMAKE_INCLUDE_PATH=$HOME/lib/${COMPILER}/usr/local/include -DCMAKE_LIBRARY_PATH=$HOME/lib/${COMPILER}/usr/local/lib  -DBUILD_TESTS_TEC=True ..
  - make
  - ls
  - ./bin/UNIT_TEST

notifications:
  irc:
    channels:
#      - "chat.freenode.net#project-trillek"
      - "chat.freenode.net#trillek"
    on_success: change
    on_failure: always

deploy: 
  provider: releases
  api_key: "OAUTH TOKEN"
  file: "TEC"
  skip_cleanup: true
  on:
    tags: true
